# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rpredict.proto\":\n\x07request\x12\x13\n\x04info\x18\x01 \x01(\x0b\x32\x05.Info\x12\x1a\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0c.RequestData\"\x14\n\x04Info\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"-\n\x0bRequestData\x12\x1e\n\x06\x66ields\x18\x01 \x01(\x0b\x32\x0e.RequestFields\"\xb0\x01\n\rRequestFields\x12\x1b\n\x04name\x18\x01 \x01(\x0b\x32\r.RequestField\x12\x1f\n\x08idnumber\x18\x02 \x01(\x0b\x32\r.RequestField\x12\x1f\n\x08\x62irthday\x18\x03 \x01(\x0b\x32\r.RequestField\x12\x1e\n\x07\x61\x64\x64ress\x18\x04 \x01(\x0b\x32\r.RequestField\x12 \n\tresidence\x18\x05 \x01(\x0b\x32\r.RequestField\"/\n\x0cRequestField\x12\x0f\n\x07\x63uttype\x18\x01 \x01(\t\x12\x0e\n\x06images\x18\x02 \x03(\t\"<\n\x08response\x12\x13\n\x04info\x18\x01 \x01(\x0b\x32\x05.Info\x12\x1b\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\r.ResponseData\"/\n\x0cResponseData\x12\x1f\n\x06\x66ields\x18\x01 \x01(\x0b\x32\x0f.ResponseFields\"\xb6\x01\n\x0eResponseFields\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.ResponseField\x12 \n\x08idnumber\x18\x02 \x01(\x0b\x32\x0e.ResponseField\x12 \n\x08\x62irthday\x18\x03 \x01(\x0b\x32\x0e.ResponseField\x12\x1f\n\x07\x61\x64\x64ress\x18\x04 \x01(\x0b\x32\x0e.ResponseField\x12!\n\tresidence\x18\x05 \x01(\x0b\x32\x0e.ResponseField\"-\n\rResponseField\x12\x1c\n\tword_cans\x18\x01 \x03(\x0b\x32\t.WordCans\"6\n\x08WordCans\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x1c\n\tchar_cans\x18\x02 \x03(\x0b\x32\t.CharCans\"\x1f\n\x08\x43harCans\x12\x13\n\x04prob\x18\x01 \x03(\x0b\x32\x05.Prob\"\"\n\x04Prob\x12\x0c\n\x04\x63har\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\x32\'\n\x03OCR\x12 \n\x07Predict\x12\x08.request\x1a\t.response\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='request.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='request.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=75,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='Info.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=97,
)


_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='RequestData.fields', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=144,
)


_REQUESTFIELDS = _descriptor.Descriptor(
  name='RequestFields',
  full_name='RequestFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RequestFields.name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idnumber', full_name='RequestFields.idnumber', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='RequestFields.birthday', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='RequestFields.address', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='residence', full_name='RequestFields.residence', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=323,
)


_REQUESTFIELD = _descriptor.Descriptor(
  name='RequestField',
  full_name='RequestField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cuttype', full_name='RequestField.cuttype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='RequestField.images', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=372,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='response.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='response.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=434,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='ResponseData.fields', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=483,
)


_RESPONSEFIELDS = _descriptor.Descriptor(
  name='ResponseFields',
  full_name='ResponseFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ResponseFields.name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idnumber', full_name='ResponseFields.idnumber', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='ResponseFields.birthday', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ResponseFields.address', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='residence', full_name='ResponseFields.residence', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=668,
)


_RESPONSEFIELD = _descriptor.Descriptor(
  name='ResponseField',
  full_name='ResponseField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word_cans', full_name='ResponseField.word_cans', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=715,
)


_WORDCANS = _descriptor.Descriptor(
  name='WordCans',
  full_name='WordCans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='WordCans.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='char_cans', full_name='WordCans.char_cans', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=717,
  serialized_end=771,
)


_CHARCANS = _descriptor.Descriptor(
  name='CharCans',
  full_name='CharCans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prob', full_name='CharCans.prob', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=804,
)


_PROB = _descriptor.Descriptor(
  name='Prob',
  full_name='Prob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='char', full_name='Prob.char', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prob', full_name='Prob.prob', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=806,
  serialized_end=840,
)

_REQUEST.fields_by_name['info'].message_type = _INFO
_REQUEST.fields_by_name['data'].message_type = _REQUESTDATA
_REQUESTDATA.fields_by_name['fields'].message_type = _REQUESTFIELDS
_REQUESTFIELDS.fields_by_name['name'].message_type = _REQUESTFIELD
_REQUESTFIELDS.fields_by_name['idnumber'].message_type = _REQUESTFIELD
_REQUESTFIELDS.fields_by_name['birthday'].message_type = _REQUESTFIELD
_REQUESTFIELDS.fields_by_name['address'].message_type = _REQUESTFIELD
_REQUESTFIELDS.fields_by_name['residence'].message_type = _REQUESTFIELD
_RESPONSE.fields_by_name['info'].message_type = _INFO
_RESPONSE.fields_by_name['data'].message_type = _RESPONSEDATA
_RESPONSEDATA.fields_by_name['fields'].message_type = _RESPONSEFIELDS
_RESPONSEFIELDS.fields_by_name['name'].message_type = _RESPONSEFIELD
_RESPONSEFIELDS.fields_by_name['idnumber'].message_type = _RESPONSEFIELD
_RESPONSEFIELDS.fields_by_name['birthday'].message_type = _RESPONSEFIELD
_RESPONSEFIELDS.fields_by_name['address'].message_type = _RESPONSEFIELD
_RESPONSEFIELDS.fields_by_name['residence'].message_type = _RESPONSEFIELD
_RESPONSEFIELD.fields_by_name['word_cans'].message_type = _WORDCANS
_WORDCANS.fields_by_name['char_cans'].message_type = _CHARCANS
_CHARCANS.fields_by_name['prob'].message_type = _PROB
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['RequestFields'] = _REQUESTFIELDS
DESCRIPTOR.message_types_by_name['RequestField'] = _REQUESTFIELD
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['ResponseFields'] = _RESPONSEFIELDS
DESCRIPTOR.message_types_by_name['ResponseField'] = _RESPONSEFIELD
DESCRIPTOR.message_types_by_name['WordCans'] = _WORDCANS
DESCRIPTOR.message_types_by_name['CharCans'] = _CHARCANS
DESCRIPTOR.message_types_by_name['Prob'] = _PROB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:request)
  ))
_sym_db.RegisterMessage(request)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
  DESCRIPTOR = _INFO,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:Info)
  ))
_sym_db.RegisterMessage(Info)

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDATA,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:RequestData)
  ))
_sym_db.RegisterMessage(RequestData)

RequestFields = _reflection.GeneratedProtocolMessageType('RequestFields', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTFIELDS,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:RequestFields)
  ))
_sym_db.RegisterMessage(RequestFields)

RequestField = _reflection.GeneratedProtocolMessageType('RequestField', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTFIELD,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:RequestField)
  ))
_sym_db.RegisterMessage(RequestField)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:response)
  ))
_sym_db.RegisterMessage(response)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEDATA,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:ResponseData)
  ))
_sym_db.RegisterMessage(ResponseData)

ResponseFields = _reflection.GeneratedProtocolMessageType('ResponseFields', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEFIELDS,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:ResponseFields)
  ))
_sym_db.RegisterMessage(ResponseFields)

ResponseField = _reflection.GeneratedProtocolMessageType('ResponseField', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEFIELD,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:ResponseField)
  ))
_sym_db.RegisterMessage(ResponseField)

WordCans = _reflection.GeneratedProtocolMessageType('WordCans', (_message.Message,), dict(
  DESCRIPTOR = _WORDCANS,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:WordCans)
  ))
_sym_db.RegisterMessage(WordCans)

CharCans = _reflection.GeneratedProtocolMessageType('CharCans', (_message.Message,), dict(
  DESCRIPTOR = _CHARCANS,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:CharCans)
  ))
_sym_db.RegisterMessage(CharCans)

Prob = _reflection.GeneratedProtocolMessageType('Prob', (_message.Message,), dict(
  DESCRIPTOR = _PROB,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:Prob)
  ))
_sym_db.RegisterMessage(Prob)



_OCR = _descriptor.ServiceDescriptor(
  name='OCR',
  full_name='OCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=842,
  serialized_end=881,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='OCR.Predict',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR)

DESCRIPTOR.services_by_name['OCR'] = _OCR

# @@protoc_insertion_point(module_scope)
